### ISSUE TITLE
Digging hard for help, trying to contact you

### ISSUE THREAD

**Issue by AckerApple** [jamesmh/event-sourcing-typescript-lessons#1]
In 2021 you wrote an article about NestJs and EventStore client, [here](https://www.eventstore.com/blog/building-a-nestjs-web-application-with-eventstoredb). I could not find a better way to contact you, at this time.

We used your article back then with great success. However several times since we have tried to upgrade to NestJs9 but we encounter an error on deploy that has me all over the place trying to settle it. I know this is not a you problem but reaching out incase you've encountered issues or changed the way you setup `@eventstore/db-client` today.

Feel free to ignore and do not feel obligated to help. Thank you kindly in advanced

We get the following issue upon upgrade:

```
access-denied: 7 PERMISSION_DENIED: Access Denied
Error: 7 PERMISSION_DENIED: Access Denied

at convertToCommandError (/app/node_modules/@eventstore/db-client/dist/utils/CommandError.js:337:20)
at ClientDuplexStreamImpl.<anonymous> (/app/node_modules/@eventstore/db-client/dist/persistentSubscription/utils/PersistentSubscriptionImpl.js:30:69)
at ClientDuplexStreamImpl.emit (node:events:529:35)
at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:419:28)
at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Our upgrade, currently consists of the following commands, which doesn't even include updating event store:
```
npm install @nestjs/common@9.4.3
npm install @nestjs/core@9.4.3 --force
npm install @nestjs/config@2.2.0 --force
npm install @nestjs/axios@3.0.0 --force
npm install @nestjs/platform-express@9.4.3 --force
npm install @nestjs/event-emitter@1.4.2 --force
npm install @nestjs/microservices@9.4.3 --force
npm install @nestjs/schedule@2.2.3 --force
npm install @nestjs/mongoose@9.2.2 --force
npm install @nestjs/swagger@7.0.12 --force
npm install @nestjs/terminus@9.2.2 --force
npm install dd-trace@3.55.0 --force
npm install nestjs-ddtrace@3.0.2 --force
npm install @nestjs/testing@9.3.12 --force
npm install nestjs-request-context@2.1.0
npm install @nestjs/websockets@9.4.3
npm install @nestjs/cli@9.5.0
npm install @nestjs/config@2.2.0
```

**Comment by AckerApple** [comment]
Nevermind sorry to bother. In case someone else is searching the internet like I was and finds this page...

It was dd-trace that was the issue. I removed the following from my install and the upgrade worked:

REMOVED
```
npm install dd-trace@3.55.0 --force
npm install nestjs-ddtrace@3.0.2 --force
```
